### ISSUE TITLE
Code blocks have preceeding spaces

### ISSUE THREAD

**Issue by StuartJMackintosh** [OpusVL/perldoc.perl.org#11]
When copied / pasted, the code blocks are indented with spaces.

For example, selecting a code block from this page:[https://perldoc2.perl.org/5/28/1/perlreftut.html](https://perldoc2.perl.org/5/28/1/perlreftut.html) pastes like this:
```
    	Finland: Helsinki.
    	Germany: Berlin, Frankfurt.
    	USA:  Chicago, New York, Washington.
```
Which then requires the spaces to be manually removed.

I would expect this:

```
Finland: Helsinki.
Germany: Berlin, Frankfurt.
USA:  Chicago, New York, Washington.
```

**Comment by JohnMica** [comment]
this is due to the ptidy extracting the code from the POD.

having links inside the 'code blocks' means that they are not really code block but ordered lists with links to pages ( clicking on `use` will take the user the the `use.html` page - as an example)

for now this is how it will work until we have some other library that will extract pod code differently
