### ISSUE TITLE
URL structure is odd

### ISSUE THREAD

**Issue by rspier** [OpusVL/perldoc.perl.org#2]
I understand the logic behind /5/28/1/, but /5.28.1/ would be clearer.

**Comment by JohnMica** [comment]
indeed it would be,
however it would not be an easy way to achieve that considering the way the scripts are done

**Comment by StuartJMackintosh** [comment]
The suggestion by @rspier makes sense from a Perl perspective although the builder scripts will need some work to achieve as the version split literally builds up the path for storage. Who created the script? Was it @JJ-OpusVL ? if so, he may have a view on the effort required for this change.

Possibly this could be fixed with a proxy hack if the script change is too onerous although these often bite back.

In any case, can this be added to a roadmap / todo category?

**Comment by rspier** [comment]
I did a proof of concept, and @abh has implemented Apache rewrites to solve this, but it would still be better to just generate the paths the other way.  Seems like it shouldn't be so bad to do.

**Comment by JohnMica** [comment]
updated URL structure to reflect 5.24.2 instead of 5/24/2

code is ready for testing on the staging env if you want to 

http://perldoc.projects.opusvl.com

**Comment by rspier** [comment]
Thank you!
