### ISSUE TITLE
links into sections lead to malpositioned content view

### ISSUE THREAD

**Issue by Wolf-at-SO** [OpusVL/perldoc.perl.org#52]
If I click on a link with an #anchor attached, I **expect** to get to a section *at* the title, which means, I see the section title at the top of the viewport. What I **observe** on the perldoc site is that the title is hidden.

This was also the case in the old perldoc implementation. I hope this is not considered "a feature" ;)
BTW: perldoc.pl does it right (as most websites around).

Here is an example:
* bad: https://perldoc.perl.org/5.30.0/perlform.html#DESCRIPTION
* good: https://perldoc.pl/perlform#DESCRIPTION

**Comment by Wolf-at-SO** [comment]
Sorry it's even more confusing: If I follow the link https://perldoc.perl.org/5.30.0/perlform.html#DESCRIPTION, I get the correct position. If I position the cursor into the address line and press [enter], I see the title hidden. If I press [F5] the title is there again.
If I click on a section title in the TOC, I get, again, to the section *behind* the title.

What is causing this strange inconsistency?

**Comment by JohnMica** [comment]
thanks for this report.

because the 2 different sites use different types of navigation bar  (static vs fixed) position this can happen. even if the text is still on the page it is positioned under the navigation.

this has been looked into and a fix provided.

should be available to see the change rather soon.

**Comment by JohnMica** [comment]
i believe this has not been fixed in the new beta release
