### ISSUE TITLE
PgUp and PgDown do not work

### ISSUE THREAD

**Issue by aluaces** [OpusVL/perldoc.perl.org#53]
The navbar takes the input focus from the beginning, so PgUp, PgDown or Space keys do not scroll unless the main space is clicked previously with the mouse in order to regain the focus.

**Comment by hakonhagland** [comment]
See also issue #16

**Comment by JohnMica** [comment]
this is due to the magic of `object` tags used for svg. It is a strange bug / feature and it will block any type of keyboard navigation.

there is some documentation on this but for the most part there is no 'standardized fix' as browsers didn't seem to care that much about this.

it has been looked into and we have decided to not use the `object` tag to avoid different browsers 'lack of / buggy' implementation and moved to use `img` tags. 

in our testing this has been solved.

a new release of the site is planned soon

**Comment by JohnMica** [comment]
this has been released in the new beta
